GUI:
  height:
    type: entry
  width:
    type: entry
  border:
    type: dropdown
    options:
      - rounded
      - transparent
      - none
  buttons:
    type: subsection
    block:
      height:
        type: entry
      width:
        type: entry
      clickable:
        type: checkbox